@startuml
'http://plantuml.com/skinparam.html
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Utente as Actor
participant Utente.ConsoleApp as System

Actor -> System: Choose Meal Booking Option

note right of System: Validate if user balance > 0?\nYes

System -> Actor: Ask to choose date
Actor -> System: Enters Date

note right of System: Should the system ommit meal types\nthat are no longer available?\nYes
note right of System: Should the system ommit meals for\nwhich the user does not have credit?
note right of System: Should the list display all meals\nfor the day or only for the\nspecified meal type?\nDisplaying all meals for choosen day.
note right of System: Should the system ommit meals\nthat are no longer available?\nYes. Listing all and displaying message\nif not available.

System -> Actor: List available meal for day
System -> Actor: Ask to choose meal
Actor -> System: Enters meals
System -> Actor: Meal booking confirmation

@enduml