@startuml use-case-realization2.svg

participant Kiosk <<client>>

BookingDaemon -> BookingServer : new
loop true
BookingDaemon -> BookingServer: start
Activate BookingServer
BookingServer -> BookingServer: accept

Kiosk --> BookingServer: request

participant HandleClient <<thread>>
activate HandleClient
BookingServer -\ HandleClient: start
deactivate BookingServer
end

HandleClient -> MessageParser:parse(request)
create BookingProtocolRequest <<abstract>>
MessageParser -> BookingProtocolRequest:new

HandleClient -> BookingProtocolRequest: execute
activate BookingProtocolRequest
BookingProtocolRequest -> BookingProtocolRequest:buildResponse
BookingProtocolRequest --> HandleClient: response
deactivate BookingProtocolRequest

HandleClient --> Kiosk: response
deactivate HandleClient

@enduml